[package]
name = "cargo-check-delta"
version = "0.1.0"
edition = "2024"

[dependencies]
cargo_metadata = "0.19.1"
clap = { version = "4.5.30", features = ["derive"] }
ignore = "0.4.23"
serde = "1.0.217"
serde_json = "1.0.138"
